// <auto-generated />
using System;
using BankUsersApp.Infrastructure.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankUsersApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankUsersApp.Infrastructure.Models.Banks", b =>
                {
                    b.Property<long>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BankId"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("BankId");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            BankId = 1L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8187),
                            BankName = "FNB",
                            Status = true
                        },
                        new
                        {
                            BankId = 2L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8198),
                            BankName = "Capitec",
                            Status = true
                        },
                        new
                        {
                            BankId = 3L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8199),
                            BankName = "Netbank",
                            Status = true
                        });
                });

            modelBuilder.Entity("BankUsersApp.Infrastructure.Models.UserBankDetail", b =>
                {
                    b.Property<long>("UserBankDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserBankDetailId"));

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("BankId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("UserBankDetailId");

                    b.ToTable("UserBankDetail");

                    b.HasData(
                        new
                        {
                            UserBankDetailId = 1L,
                            AccountNumber = "427560404",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8446),
                            AvailableBalance = 5000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 1L
                        },
                        new
                        {
                            UserBankDetailId = 4L,
                            AccountNumber = "368475743",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8469),
                            AvailableBalance = 7000.00m,
                            BankId = 2L,
                            Status = true,
                            UserId = 2L
                        },
                        new
                        {
                            UserBankDetailId = 5L,
                            AccountNumber = "359163664",
                            AccountType = "Savings",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8473),
                            AvailableBalance = 15000.00m,
                            BankId = 3L,
                            Status = true,
                            UserId = 2L
                        },
                        new
                        {
                            UserBankDetailId = 6L,
                            AccountNumber = "100938456",
                            AccountType = "Savings",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8478),
                            AvailableBalance = 9000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 3L
                        },
                        new
                        {
                            UserBankDetailId = 8L,
                            AccountNumber = "410465792",
                            AccountType = "Savings",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8480),
                            AvailableBalance = 6000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 4L
                        },
                        new
                        {
                            UserBankDetailId = 9L,
                            AccountNumber = "483105399",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8488),
                            AvailableBalance = 12000.00m,
                            BankId = 3L,
                            Status = true,
                            UserId = 4L
                        },
                        new
                        {
                            UserBankDetailId = 10L,
                            AccountNumber = "346645962",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8491),
                            AvailableBalance = 8000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 5L
                        },
                        new
                        {
                            UserBankDetailId = 11L,
                            AccountNumber = "493682017",
                            AccountType = "Fixed Deposit",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8495),
                            AvailableBalance = 30000.00m,
                            BankId = 2L,
                            Status = true,
                            UserId = 5L
                        },
                        new
                        {
                            UserBankDetailId = 12L,
                            AccountNumber = "346399646",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8499),
                            AvailableBalance = 6500.00m,
                            BankId = 2L,
                            Status = true,
                            UserId = 6L
                        },
                        new
                        {
                            UserBankDetailId = 13L,
                            AccountNumber = "664869602",
                            AccountType = "Savings",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8505),
                            AvailableBalance = 11000.00m,
                            BankId = 3L,
                            Status = true,
                            UserId = 6L
                        },
                        new
                        {
                            UserBankDetailId = 14L,
                            AccountNumber = "949732954",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8508),
                            AvailableBalance = 4000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 7L
                        },
                        new
                        {
                            UserBankDetailId = 15L,
                            AccountNumber = "323277976",
                            AccountType = "Savings",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8511),
                            AvailableBalance = 9500.00m,
                            BankId = 2L,
                            Status = true,
                            UserId = 8L
                        },
                        new
                        {
                            UserBankDetailId = 16L,
                            AccountNumber = "421648190",
                            AccountType = "Cheque",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8602),
                            AvailableBalance = 5500.00m,
                            BankId = 3L,
                            Status = true,
                            UserId = 9L
                        },
                        new
                        {
                            UserBankDetailId = 17L,
                            AccountNumber = "895261861",
                            AccountType = "Fixed Deposit",
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8608),
                            AvailableBalance = 18000.00m,
                            BankId = 1L,
                            Status = true,
                            UserId = 10L
                        });
                });

            modelBuilder.Entity("BankUsersApp.Infrastructure.Models.Users", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserId"));

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResidentialAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8350),
                            DateOfBirth = new DateTime(1987, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "TomasDDavis@dayrep.com",
                            FirstName = "Tomas",
                            IdNumber = "8708139333082",
                            LastName = "Davis",
                            MobileNumber = "27833653254",
                            Password = "password1",
                            ResidentialAddress = "1626 Prospect St Laudium 0037",
                            Status = true
                        },
                        new
                        {
                            UserId = 2L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8353),
                            DateOfBirth = new DateTime(1995, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "LuzCGillespie@dayrep.com",
                            FirstName = "Luz",
                            IdNumber = "9507241481188",
                            LastName = "Gillespie",
                            MobileNumber = "27828566711",
                            Password = "password2",
                            ResidentialAddress = "1342 Sandown Rd Cape Town 8002",
                            Status = true
                        },
                        new
                        {
                            UserId = 3L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8355),
                            DateOfBirth = new DateTime(1953, 8, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JeanJMasters@rhyta.com",
                            FirstName = "Jean",
                            IdNumber = "5308284995083",
                            LastName = "Masters",
                            MobileNumber = "27842302921",
                            Password = "password3",
                            ResidentialAddress = "334 Daffodil Dr Mqanduli 5085",
                            Status = true
                        },
                        new
                        {
                            UserId = 4L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8361),
                            DateOfBirth = new DateTime(1944, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MelissaCHennigan@teleworm.us",
                            FirstName = "Melissa",
                            IdNumber = "4411110823080",
                            LastName = "Hennigan",
                            MobileNumber = "27836601180",
                            Password = "password4",
                            ResidentialAddress = "772 North Street Utrecht 2980",
                            Status = true
                        },
                        new
                        {
                            UserId = 5L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8362),
                            DateOfBirth = new DateTime(1963, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "JoshuaLRohrer@armyspy.com",
                            FirstName = "Joshua",
                            IdNumber = "6304128535184",
                            LastName = "Rohrer",
                            MobileNumber = "27849978318",
                            Password = "password5",
                            ResidentialAddress = "577 Gray Pl Durban 4061",
                            Status = true
                        },
                        new
                        {
                            UserId = 6L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8364),
                            DateOfBirth = new DateTime(1983, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "NathanielPOlson@armyspy.com",
                            FirstName = "Nathaniel",
                            IdNumber = "8312107886088",
                            LastName = "Olson",
                            MobileNumber = "27842399367",
                            Password = "password6",
                            ResidentialAddress = "570 Gemsbok St Pietersburg 0780",
                            Status = true
                        },
                        new
                        {
                            UserId = 7L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8366),
                            DateOfBirth = new DateTime(2001, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "RebeccaJMack@armyspy.com",
                            FirstName = "Rebecca",
                            IdNumber = "106064473080",
                            LastName = "Mack",
                            MobileNumber = "27839078572",
                            Password = "password7",
                            ResidentialAddress = "995 Loop St Hopefield 7355 Curious ",
                            Status = true
                        },
                        new
                        {
                            UserId = 8L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8368),
                            DateOfBirth = new DateTime(1972, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ErvinDRandolph@dayrep.com",
                            FirstName = "Ervin",
                            IdNumber = "7201255800085",
                            LastName = "Randolph",
                            MobileNumber = "27824672109",
                            Password = "password8",
                            ResidentialAddress = "349 Old Cres Indwe 5445",
                            Status = true
                        },
                        new
                        {
                            UserId = 9L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8370),
                            DateOfBirth = new DateTime(1938, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "EmikoRSloan@armyspy.com",
                            FirstName = "Emiko",
                            IdNumber = "3807210295080",
                            LastName = "Sloan",
                            MobileNumber = "27843555547",
                            Password = "password9",
                            ResidentialAddress = "297 Glyn St Silverton 0170",
                            Status = true
                        },
                        new
                        {
                            UserId = 10L,
                            AddedOn = new DateTime(2023, 6, 30, 18, 1, 49, 93, DateTimeKind.Local).AddTicks(8371),
                            DateOfBirth = new DateTime(1939, 10, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "MichaelRShew@teleworm.us",
                            FirstName = "Michael",
                            IdNumber = "3910139902180",
                            LastName = "Shew",
                            MobileNumber = "27833368984",
                            Password = "password10",
                            ResidentialAddress = "1747 Impala St Dalton 3242",
                            Status = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
